-- Resetting the Auto inc. to 1 in case there were some values before in the table.
ALTER TABLE `Books` AUTO_INCREMENT = 1;
INSERT INTO `VPLibrary`.`Books` (`Book_name`, `Auth_name`, `Auth_surname`, `Publish_year`, `Publish_house`, `Book_description`, `Genre`) VALUES 
-- The Ice Princess - Camila Lackberg
('The Ice Princess', 'Camila', 'Lackberg', 2003, 'Harper Collins', 
'Erica Falck has returned to her family home in Fjällbacka after her parents died. While coping with the death of her parents, she is trying to work on a biography of Selma Lagerlöf, a Swedish author and the first female writer to win the Nobel Prize in Literature.
Patrick Hedström, a detective, is assigned to investigate a case in which the victim, Erica''s childhood friend Alex, is frozen in a bathtub. The investigation shows that the young woman''s death occurred before she was placed in the tub, allowing the liquid to freeze around her as the temperature dropped far below freezing inside her apartment. Exactly when the furnace went out-of-order is a timely coincidence to the alleged suicide.
At the prompting of Alex''s parents, Erica begins to investigate the death of their daughter. Her breakthrough comes when she meets a police officer who is also investigating the mystery; together the two uncover dark secrets within the town. Erica and Patrick''s fascination gives way to deep obsession as they struggle to determine the true circumstances surrounding the death.[4] Erica visualizes a memoir about Alex, one that will answer questions about their missing friendship.',
'Horror'),
-- The Death of Ivan Ilyich - Lev Tolstoi
('The Death of Ivan Ilyich', 'Lev', 'Tolstoi', 1886, 'Oto Antonini', 
'van Ilyich lives a carefree life that is "most simple and most ordinary and therefore most terrible". Like everyone he knows, he spends his life climbing the social ladder. Enduring marriage to a woman whom he often finds too demanding, he works his way up to be a magistrate, thanks to the influence he has over a friend who has just been promoted, focusing more on his work as his family life becomes less tolerable.
While hanging curtains for his new home one day, he falls awkwardly and hurts his side. Though he does not think much of it at first, he begins to suffer from a pain in his side. As his discomfort grows, his behavior towards his family becomes more irritable. His wife finally insists that he visit a physician. The physician cannot pinpoint the source of his malady, but soon it becomes clear that his condition is terminal. Confronted with his diagnosis, Ivan attempts every remedy he can to obtain a cure for his worsening situation until the pain grows so intense he is forced to cease working and spend the remainder of his days in bed. Here, he is brought face to face with his mortality, and realizes that although he knows of it, he does not truly grasp it.
During the long and painful process of death, Ivan dwells on the idea that he does not deserve his suffering because he has lived rightly. If he had not lived a good life, there could be a reason for his pain; but he has, so pain and death must be arbitrary and senseless. As he begins to hate his family for avoiding the subject of his death, for pretending he is only sick and not dying, he finds his only comfort in his peasant boy servant Gerasim, the only person in Ivan''s life who does not fear death, and also the only one who, apart from his own son, shows compassion for him. Ivan begins to question whether he has, in fact, lived a good life.
In the final days of his life, Ivan makes a clear split between an artificial life, such as his own, which masks the true meaning of life and makes one fear death, and an authentic life, the life of Gerasim. Authentic life is marked by compassion and sympathy; the artificial life by self-interest. Then "some force" strikes Ivan in the chest and side, and he is brought into the presence of a bright light. His hand falls onto his nearby son''s head, and Ivan pities his son. He no longer hates his daughter or wife, but rather feels pity for them, and hopes his death will release them. In so doing, his terror of death leaves him, and as Tolstoy suggests, death itself disappears.',
'Drama'),
-- Eugen Onegin - Alexander S. Pushkin
('Eugene Onegin', 'Alexander', 'S. Pushkin', 1833, 'None', 
'In the 1820s, Eugene Onegin is a bored Saint Petersburg dandy, whose life consists of balls, concerts, parties and nothing more. One day he inherits a landed estate from his uncle. When he moves to the country, he strikes up a friendship with his neighbor, a starry-eyed young poet named Vladimir Lensky. One day, Lensky takes Onegin to dine with the family of his fiancée, the sociable but rather thoughtless Olga Larina. At this meeting he also catches a glimpse of Olga''s sister Tatyana. A quiet, precocious romantic and the exact opposite of Olga, Tatyana becomes intensely drawn to Onegin. Soon after, she bares her soul to Onegin in a letter professing her love. Contrary to her expectations, Onegin does not write back. When they meet in person, he rejects her advances politely but dismissively and condescendingly. This famous speech is often referred to as Onegin''s Sermon: he admits that the letter was touching, but says that he would quickly grow bored with marriage and can only offer Tatyana friendship; he coldly advises more emotional control in the future, lest another man take advantage of her innocence.
Onegin by Dmitry Kardovsky, 1909
Later, Lensky mischievously invites Onegin to Tatyana''s name day celebration promising a small gathering with just Tatyana, Olga, and their parents. When Onegin arrives, he finds instead a boisterous country ball, a rural parody of and contrast to the society balls of St. Petersburg he has grown tired of. Onegin is irritated with the guests who gossip about him and Tatyana, and with Lensky for persuading him to come.reluctantly accepts, feeling compelled by social convention. During the duel, Onegin unwillingly kills Lensky. Afterwards, he quits his country estate, traveling abroad to deaden his feelings of remorse.
Tatyana visits Onegin''s mansion, where she looks through his books and his notes in the margins, and begins to question whether Onegin''s character is merely a collage of different literary heroes, and if there is, in fact, no "real Onegin".
Several years pass, and the scene shifts to St. Petersburg. Onegin has come to attend the most prominent balls and interact with the leaders of old Russian society. He sees the most beautiful woman, who captures the attention of all and is central to society''s whirl, and he realizes that it is the same Tatyana whose love he had once turned away. Now she is married to an aged prince. Upon seeing Tatyana again, he becomes obsessed with winning her affection, despite the fact that she is married. However, his attempts are rebuffed.. Onegin repeats his love for her. Faltering for a moment, she admits that she still loves him, but she will not allow him to ruin her and declares her determination to remain faithful to her husband. She leaves him regretting his bitter destiny.',
'Drama'),
-- Sense and sensibility - Jane Austen
('Sense and Sensibility', 'Jane', 'Austen', 1811, 'Military Library', 
'Austen biographer Claire Tomalin argues that Sense and Sensibility has a "wobble in its approach," which developed because Austen, in the course of writing the novel, gradually became less certain about whether sense or sensibility should triumph.[6] Austen characterises Marianne as a sweet lady with attractive qualities: intelligence, musical talent, frankness, and the capacity to love deeply. She also acknowledges that Willoughby, with all his faults, continues to love and, in some measure, appreciate Marianne. For these reasons, some readers find Marianne''s ultimate marriage to Colonel Brandon an unsatisfactory ending.[7] Other interpretations, however, have argued that Austen''s intention was not to debate the superior value of either sense or sensibility in good judgment, but rather to demonstrate that both are equally important but must be applied with good balance to one another.
Dashwood extracts a promise from his son, that he will take care of his half-sisters; however, John''s selfish and greedy wife, Fanny, soon persuades him to renege. John and Fanny immediately take up their place as the new owners of Norland, while the Dashwood women are reduced to the position of unwelcome guests. Mrs. Dashwood begins looking for somewhere else to live.In the meantime, the Steele sisters have come to London as guests of John and Fanny Dashwood. Lucy sees her invitation to the Dashwoods'' as a personal compliment, rather than what it is, a slight to Elinor. In the false confidence of their popularity, Anne Steele betrays Lucy''s secret. As a result the Misses Steele are turned out of the house, and Edward is entreated to break the engagement on pain of disinheritance. Edward, honourably, refuses to comply and is immediately disinherited in favour of his brother, gaining widespread respect for his gentlemanly conduct, and sympathy from Elinor and Marianne who understand how much he has sacrificed. Colonel Brandon shows this admiration by offering him the living of Delaford parsonage.
Mrs. Jennings takes Elinor and Marianne to the country to visit her second daughter who has just given birth to her first child. In her misery over Willoughby''s marriage, Marianne neglects her health and becomes dangerously ill. Traumatised by rumours of her impending death, Willoughby arrives to repent and reveals to Elinor that his love for Marianne was genuine. When his aunt learned of his behaviour towards Miss Williams and disinherited him, he felt he had to marry for money rather than love. But he elicits Elinor''s pity because his choice has made him unhappy.
When Marianne recovers, Elinor tells her of Willoughby''s visit. Marianne comes to assess what has passed with sense rather than emotion, and sees that she could never have been happy with Willoughby''s immoral and expansive nature. She comes to value Elinor''s conduct in a similar situation and resolves to model herself after Elinor''s courage and good sense.
On learning that Lucy has married Mr. Ferrars, Elinor grieves, until Edward arrives and reveals that, after his disinheritance, Lucy jilted him in favour of his now wealthy brother, Robert Ferrars. Edward and Elinor soon marry, and in a very few years Marianne marries Colonel Brandon, having gradually fallen deeply in love with him.',
'Romance'),
-- Emma - Jane Austen
('Emma', 'Jane', 'Austen', 1815, 'Military Library',
'Emma, by Jane Austen, is a novel about youthful hubris and the perils of misconstrued romance. The novel was first published in December 1815. As in her other novels, Austen explores the concerns and difficulties of genteel women living in Georgian-Regency England; she also creates a lively comedy of manners among her characters.
Before she began the novel, Austen wrote, "I am going to take a heroine whom no one but myself will much like. In the very first sentence she introduces the title character as "Emma Woodhouse, handsome, clever, and rich." Emma, however, is also rather spoiled, headstrong, and self-satisfied; she greatly overestimates her own matchmaking abilities; she is blind to the dangers of meddling in other people''s lives; and her imagination and perceptions often lead her astray.'
,'Romance'),
-- Pride and Prejudice - Jane Austen
('Pride and Prejudice', 'Jane', 'Austen', 1813, 'Military Library',
'Pride and Prejudice is a novel of manners by Jane Austen, first published in 1813. The story follows the main character, Elizabeth Bennet, as she deals with issues of manners, upbringing, morality, education, and marriage in the society of the landed gentry of the British Regency. Elizabeth is the second of five daughters of a country gentleman living near the fictional town of Meryton in Hertfordshire, near London.
Page 2 of a letter from Jane Austen to her sister Cassandra (11 June 1799) in which she first mentions Pride and Prejudice, using its working title First Impressions. (NLA)
Set in England in the early 19th century, Pride and Prejudice tells the story of Mr and Mrs Bennet''s five unmarried daughters after the rich and eligible Mr Bingley and his status-conscious friend, Mr Darcy, have moved into their neighbourhood. While Bingley takes an immediate liking to the eldest Bennet daughter, Jane, Darcy has difficulty adapting to local society and repeatedly clashes with the second-eldest Bennet daughter, Elizabeth.
Pride and Prejudice retains a fascination for modern readers, continuing near the top of lists of "most loved books." It has become one of the most popular novels in English literature, selling over 20 million copies, and receives considerable attention from literary scholars. Modern interest in the book has resulted in a number of dramatic adaptations and an abundance of novels and stories imitating Austen''s memorable characters or themes.',
'Romance'),
-- The lady of the Camellias - Alexandre Dumas
('The Lady of the Camellias', 'Alexandre', 'Dumas', 1848, 'none', 
'The theme of The Lady of the Camellias is a love story between Marguerite Gautier, a "demi-mondaine" ("courtisane" in the original French, i.e., a woman "kept" by various lovers, frequently more than one at a time) suffering from tuberculosis, and a young provincial bourgeois, Armand Duval. The narration of the love story is told by Duval himself to the (unnamed) narrator of the book. She is named as the Lady of the Camellias because she wears a white camellia when she is available to her lover(s) and a red one when her delicate condition precludes making love.Armand falls in love with Marguerite and ultimately becomes her lover, convincing her to turn her back on her life as a "courtisane" and live with him in the countryside. This idyllic existence is broken by Armand''s father, who, concerned by the scandal created by the illicit relationship and fearful that it will destroy his daughter''s (Armand''s sister''s) chances of marriage, convinces Marguerite to leave Armand, who believes, up until Marguerite''s death, that she has left him for another man. Marguerite''s death is described as an unending agony, during which Marguerite, abandoned by everyone, can only regret what might have been. Unlike the love of the Chevalier des Grieux for Manon Lescaut (to which story Dumas himself makes reference at the beginning of The Lady of the Camellias), Armand''s love is for a woman who is ready to sacrifice her riches and her lifestyle for him, but who is thwarted by the arrival of Armand''s father.
Dumas is careful to paint a favourable portrait of Marguerite, who despite her past is rendered virtuous by her love for Armand, and the suffering of the two lovers, whose love is shattered by the need to conform to the morals of the times, is rendered touchingly.
The novel is also marked by the description of Parisian life during the 19th century and the fragile world of the "courtisanes".',
'Romance'),
-- The Shadow of the Wind - Carlos Ruiz Zafron
('The Shadow of the Wind', 'Carlos Ruiz', 'Zafon', 2001,'Planeta', 
'Let''s begin with a marvelous story - one of those timeless fables that is charged with mystery and magic - the kind that provides the basis for great novels. Somewhere on a dark and lonely street in Barcelona, there is an ancient, locked building called the Cemetery of Forgotten Books. If you know the password, or if you have a friend who is willing to take you as his “guest,” you may gain entrance and wander through a labyrinth of echoing corridors of abandoned books until you become lost like the legendary Theseus. When you are finally rescued (if you are!), then you will be allowed to select a single volume with the understanding that you will return it some day - perhaps, after it has altered your life in significant ways. When Daniel Sempere, the protagonist of The Shadow of the Wind, comes to the Cemetery of Forgotten Books with his father, the ten-year-old boy takes a book entitled ... The Shadow of the Wind.
So begins an incredible journey that carries Daniel through a strange city filled with abandoned mansions, exotic cafes, fantastic bookstores, spirit-haunted graveyards and sinister prisons from which no inmate ever returns. Zafon''s novel is populated with a cast of characters that resemble the tortured, guilt-ridden lovers of Gabriel Garcia Marquez, the obsessed killers of Jorge Luis Borges and the doomed and solitary eccentrics of Charles Dickens. The Shadow of the Wind is an epic tale that alternately reads like Dante''s nightmarish descent into the underworld and Candide''s trek through a venal, corrupt and cruel world. In short, this is a hell of a book!',
'Mystery'),
-- Cutting for Stone - Abraham Verghese
('Cutting for Stone', 'Abraham', 'Verghese', 2009, 'Vintage Books', 
'The story is told by the protagonist, Marion Stone. He and his conjoined twin Shiva are born at Mission Hospital (called "Missing" in accordance with the local pronunciation), Addis Ababa, in September 1954. Their mother, Sister Mary Joseph Praise, an Indian Carmelite nun, dies during childbirth. Their father, Thomas Stone, the English surgeon of Missing, abandons them and disappears. Orphaned at birth, the pair grow up in the household of two physicians of Missing, both from Madras, the obstetrician Kalpana Hemlatha (Hema) and Abhi Ghosh. Hema names them Marion (after J. Marion Sims) and Shiva (after the Hindu deity). Ghosh teaches himself surgery to replace Stone. The tissue link between the twins has been separated at birth and the two grow up together being very close initially. Both are exposed to the changing political environment in Ethiopia. There is an unsuccessful rebellion by Haile Selassie''s bodyguard, General Mebratu. Ghosh knows he will be imprisoned in the aftermath of the coup. Through their parents, both boys are exposed to medicine and taught at the hospital. Over time, though, individual differences begin to become pronounced. When entering puberty their relationship to Genet, the daughter of Rosina, a domestic help, finally tears them apart. Marion is in love with Genet and intends to marry her, but it is Shiva who, interested in sexual pursuits, deflowers her. Marion feels betrayed. Rosina forces Genet to submit to female genital mutilation and commits suicide shortly thereafter. Genet will later join the Eritrean liberation movement. While Marion goes to medical school, his brother stays at Missing. Focused on the repair of birth-related fistulas, he takes up his surgical training with Hema eschewing a formal medical education. On his death bed, Ghosh has three wishes for Marion - to get the best medical education, to find Stone, and to forgive his brother.',
'Drama'),
-- No time for goodbye - Linwood Barclay
('No time for goodbye', 'Linwood', 'Barclay', 2007,'Orion Publishing Group', 
'No Time for Goodbye is a thriller novel written by Canadian author Linwood Barclay. The book was featured on the Richard & Judy Summer reading list of 2008 and The London Sunday Times reported in its year-end bestseller list that the novel led the paperback and hardcover fiction list.
The novel received mainly positive reviews. Emma-Lee Potter of The Daily Express called the novel "a fast-moving roller-coaster of a read" and Laura Wilson of The Guardian said "Barclay succeeds in both banging the gong and serving up a riveting, rewarding and, for the most part, plausible three courses, though you may need to take a deep breath somewhere around the coffee stage.',
'Thriller'),
-- Too close to home - Linwood Barclay
('Too close to home', 'Linwood', 'Barclay', 2008,'Orion Publishing Group', 
'Too Close to Home is a novel written by Canadian author Linwood Barclay, the author of the Richard & Judy Summer read winner "No Time For Goodbye".
When the Cutter family''s next-door-neighbours, the Langleys, are gunned down in their house one hot July night, the Cutters'' world is turned upside down. Could the killers have gone to the wrong house? At first the idea seems crazy, but gradually we discover that each of the Cutter family has a secret they''d rather keep buried.',
'Thriller'),
-- Cat and Mouse - James Patterson
('Cat and Mouse', 'James', 'Patterson', 1997,'Little, Brown and Company', 
'The book begins with Gary Soneji breaking into Alex Cross'' home in Washington DC and contemplating the murders of Cross and his family.
In London the killer dubbed Mr. Smith by the press is conducting a live autopsy. Mr. Smith explains to his victim what he will be feeling and that he envies his victim. Kyle Craig lends Alex use of the FBI helicopter to make his way to NYC. Cross meets with Goldman''s partner. They make their way to Goldman''s home in Riverdale. In the bedroom there is blood everywhere. The blood was splattered on the bed, the walls, and the floor. This was a brutal attack.
Elsewhere in a bar, Soneji pick up a woman and goes with her to her apartment. A few days later, Cross returns home. He spends the entire day with his family. Kyle Craig calls Cross and again asks for help on the Mr. Smith case. Cross says no. At the hotel, Pierce gets an e mail from Mr. Smith that he took a young surgeon in Pierce''s honor. Mr. Smith has been contacting Pierce before he commits a murder and challenges Pierce to stop him. Pierce needs to go. Sampson is not happy with it. Mr. Smith named himself after Valentine Michael Smith from the book Stranger in a Strange Land. Mr. Smith does another live autopsy on Abel Sante. The FBI set up another stakeout. Pierce shows up but keeps going in his car. Cross goes after Pierce and go on a high speed chase. The cars eventually go on a side road. Pierce loses Cross for a few minutes. When Cross and Sampson find Pierce''s car, Pierce is gone. Alex knows he wants to complete the puzzle. The S for Smith. Cross returns to Boston. At the apartment Smith had done a self autopsy. Alex tries to stop Pierce from killing himself and the two end up fighting. Sampson shoots Pierce, pointblank.',
'Mystery'),
-- The Hades Factor - Robert Ludlum
('The Hades Factor', 'Robert','Ludlum', 2000,'Orion Publishing Group', 
'The first main crisis that hits the life of Jon Smith is the Hades project, a very evil and at the same time deadly viral experiment. This virus was first tested on 6 Iraqi soldiers and 6 US soldiers in the First Gulf War to hit the world. Several years later, 3 people, a young teenage girl, a Vietnam Veteran, and a Gulf War Army Major all died of unnatural but very disturbing causes. In this Robert Ludlum novel which he co-authored with Gayle Lynds, he explains that the virus, even though it cannot be easily transmitted, gradually spreads across different parts of the world, killing almost half a million of the population. Jon''s Smith Fiancé and co-worker, Miss Sophia Russell easily identifies the symptoms and associates them with some similar to a deadly Monkey Blood Virus that she encountered back in Peru when working together with Victor Tremont. After discussing with Tremont, Rusells starts to develop the virus'' symptoms. Infuriated by the loss of his loved one, Jon Smith swears revenge on the killer, and joins hands with Randi Russell, a CIA operative who happens to be the sister of the late Sophia, and Peter Howell, who happens to be a former M16 agent of the British to uncover and take revenge on whoever was behind the virus that killed Sophia. Jon Smith reveals the whole truth to the whole world before the US president, Samuel Adams Castilla, and then goes ahead to capture Victor Tremont and hold him captive until he is officially arrested.
Despite the fact that all charges against him were dropped, Jon voluntarily quits the USAMRIID. In the meantime, Nathaniel Fredrick Klein, an enigmatic man approaches Jon and requests his honor to join the Covert-One. This gives Jon a new reason to live, and he voluntarily agrees.',
'Thriller'),
-- The Moscow Vector - Robert Ludlum
('The Moscow Vector', 'Robert', 'Ludlum', 2000,'Orion Publishing Group', 'Determined to rebuild their shattered empire, Russia''s increasingly authoritarian leaders led by Viktor Dudarev are preparing a lightning military strike designed to overrun several republics formerly part of the USSR before the West can intervene. To succeed, they must first sow confusion and fear in the ranks of their enemies, so they turn to Konstantin Malkovic who is one of the world''s wealthiest and most powerful men. By taking on the services of a cold and calculating bioscientist from the remnants of the old East German days, he finances the development of an undetectable, unstoppable and incurable bioweapon, the perfect assassin''s tool. Created using a microsopic strand of each victim''s own DNA, it is the ultimate silent killer. This bioweapon is used against leaders, analysts and other persons dangerous to the plans to great effect such that the Covert-One operatives need to act quickly. Jon Smith, approached by a Russian doctor about this disease, uncovers the plans of the Russian leaders whilst at the same time CIA operatives are closing in from another lead they have discovered. Moles and informers in various agencies make the whole plot far more interesting than would otherwise be the case, but there is a final sting in the tail...',
'Thriller'),
-- Juliet - Anne Fortier
('Juliet', 'Anne', 'Fortier', 2010,'Ballantine Books', 
'Juliet, is about a woman named Julie Jacobs who discovers that her ancestor Giulietta is the real-life Juliet of Romeo and Juliet fame. In her encounters with various descendants of the young lovers'' families, she realizes that, that the curse from the story—"A plague on both your houses!"—may be real and may be coming after her--unless she can find her Romeo. on the track to discover her real story she and her twin sister become closer and do the journey together, finding not only their real names, life and ancesters but love, true and real love',
'Romance'),
-- The Kite Runner - Khaled Hosseini
('The Kite Runner', 'Khaled', 'Hosseini', 2003,'Riverhead Books', 
'The Kite Runner is the first novel by Afghan-American author Khaled Hosseini. Published in 2003 by Riverhead Books, it tells the story of Amir, a young boy from the Wazir Akbar Khan district of Kabul, whose closest friend is Hassan, his father''s young Hazara servant. The story is set against a backdrop of tumultuous events, from the fall of Afghanistan''s monarchy through the Soviet military intervention, the exodus of refugees to Pakistan and the United States, and the rise of the Taliban regime.
Hosseini has commented that he considers The Kite Runner to be a father–son story, emphasizing the familial aspects of the narrative, an element that he continued to use in his later works.[2] Themes of guilt and redemption feature prominently in the novel, with a pivotal scene depicting an act of violence against Hassan that Amir fails to prevent. The latter half of the book centers on Amir''s attempts to atone for this transgression by rescuing Hassan''s son over two decades later.
The Kite Runner became a bestseller after being printed in paperback and was popularized in book clubs. It was a number one New York Times bestseller for over two years, with over seven million copies sold in the United States. Reviews were generally positive, though parts of the plot drew significant controversy in Afghanistan. A number of adaptations were created following publication, including a 2007 film of the same name, several stage performances, and a graphic novel.',
'Drama'),
-- A thousand splendid suns - Khaled Hosseini
('A thousand splendid suns', 'Khaled', 'Hosseini', 2007,'Riverhead Books',
'Mariam is an illegitimate child, and suffers from both the stigma surrounding her birth along with the abuse she faces throughout her marriage. Laila, born a generation later, is comparatively privileged during her youth until their lives intersect and she is also forced to accept a marriage proposal from Rasheed, Mariam''s husband.
Hosseini has remarked that he regards the novel as a "mother-daughter story" in contrast to The Kite Runner, which he considers a "father-son story". It continues some of the themes used in his previous work, such as the familial aspects, but focuses primarily on female characters and their roles in Afghan society.
A Thousand Splendid Suns was released on May 22, 2007, and received favorable prepublication reviews from Kirkus, Publishers Weekly, Library Journal, and Booklist,[ becoming a number one New York Times bestseller for fifteen weeks following its release. During its first week on the market, it sold over one million copies. Columbia Pictures purchased film rights in 2007 and confirmed intentions to create a movie adaption of the book.',
'Drama'),
-- La Peau de chagrin - Honore De Balzac
('La Peau de chagrin', 'Honore', 'De Balzac', 1831,'Charles Gosselin and Urbain Canel ','Set in early 19th-century Paris, it tells the story of a young man who finds a magic piece of shagreen that fulfills his every desire. For each wish granted, however, the skin shrinks and consumes a portion of his physical energy. La Peau de chagrin belongs to the Études philosophiques group of Balzac''s sequence of novels, La Comédie humaine.
Before the book was completed, Balzac created excitement about it by publishing a series of articles and story fragments in several Parisian journals. Although he was five months late in delivering the manuscript, he succeeded in generating sufficient interest that the novel sold out instantly upon its publication. A second edition, which included a series of twelve other "philosophical tales", was released one month later.
Although the novel uses fantastic elements, its main focus is a realistic portrayal of the excesses of bourgeois materialism. Balzac''s renowned attention to detail is used to describe a gambling house, an antique shop, a royal banquet, and other locales. He also includes details from his own life as a struggling writer, placing the main character in a home similar to the one he occupied at the start of his literary career. The central theme of La Peau de chagrin is the conflict between desire and longevity. The magic skin represents the owner''s life-force, which is depleted through every expression of will, especially when it is employed for the acquisition of power. Ignoring a caution from the shopkeeper who offers him the skin, the protagonist greedily surrounds himself with wealth, only to find himself miserable and decrepit at the story''s end.
La Peau de chagrin firmly established Balzac as a writer of significance in France. His social circle widened significantly, and he was sought eagerly by publishers for future projects. The book served as the catalyst for a series of letters he exchanged with a Polish baroness named Ewelina Hańska, who later became his wife.',
'Drama'),
-- Old Goriot - Honore De Balzac
('Old Goriot', 'Honore', 'De Balzac', 1835,'Charles Gosselin and Urbain Canel',
'Set in Paris in 1819, it follows the intertwined lives of three characters: the elderly doting Goriot; a mysterious criminal-in-hiding named Vautrin; and a naive law student named Eugène de Rastignac. Originally published in serial form during the winter of 1834/35, Le Père Goriot is widely considered Balzac''s most important novel.[1] It marks the first serious use by the author of characters who had appeared in other books, a technique that distinguishes Balzac''s fiction. The novel is also noted as an example of his realist style, using minute details to create character and subtext.
The novel takes place during the Bourbon Restoration, which brought profound changes to French society; the struggle by individuals to secure a higher social status is a major theme in the book. The city of Paris also impresses itself on the characters – especially young Rastignac, who grew up in the provinces of southern France. Balzac analyzes, through Goriot and others, the nature of family and marriage, providing a pessimistic view of these institutions.
The novel was released to mixed reviews. Some critics praised the author for his complex characters and attention to detail; others condemned him for his many depictions of corruption and greed. A favorite of Balzac''s, the book quickly won widespread popularity and has often been adapted for film and the stage. It gave rise to the French expression "Rastignac", a social climber willing to use any means to better his situation.',
'Drama'),
-- The Da Vinci Code - Dan Brown
('The Da Vinci Code', 'Dan', 'Brown', 2003,'Doubleday', 
'It follows symbologist Robert Langdon and cryptologist Sophie Neveu after a murder in the Louvre Museum in Paris, when they become involved in a battle between the Priory of Sion and Opus Dei over the possibility of Jesus Christ having been married to Mary Magdalene. The title of the novel refers, among other things, to the finding of the first murder victim in the Grand Gallery of the Louvre, naked and posed like Leonardo da Vinci''s famous drawing, the Vitruvian Man, with a cryptic message written beside his body and a pentagram drawn on his chest in his own blood.
The novel explores an alternative religious history, whose central plot point is that the Merovingian kings of France were descended from the bloodline of Jesus Christ and Mary Magdalene, ideas derived from Clive Prince''s The Templar Revelation (1997) and books by Margaret Starbird. The book also refers to The Holy Blood and the Holy Grail (1982) though Dan Brown has stated that it was not used as research material.
The Da Vinci Code provoked a popular interest in speculation concerning the Holy Grail legend and Mary Magdalene''s role in the history of Christianity. The book has, however, been extensively denounced by many Christian denominations as an attack on the Roman Catholic Church, and consistently criticized for its historical and scientific inaccuracies. The novel nonetheless became a worldwide bestseller[1] that sold 80 million copies as of 2009[2] and has been translated into 44 languages. Combining the detective, thriller and conspiracy fiction genres, it is Brown''s second novel to include the character Robert Langdon: the first was his 2000 novel Angels & Demons. In November 2004, Random House published a Special Illustrated Edition with 160 illustrations. In 2006, a film adaptation was released by Sony''s Columbia Pictures.',
'Mystery'),
-- Eragon - Christopher Paolini
('Eragon', 'Christpher', 'Paolini', 2002,'Paolini LLC', 
'A shade named Durza, along with a group of urgals, ambushes a party of elves. After he and the urgals kill the other elves, Durza attempts steal a stone that one of the female elves carries, but is foiled when she causes it to vanish. However, he renders her unconscious with a ball of fire and has her at his mercy.
Eragon is a fifteen-year-old boy who has lived with his uncle Garrow and cousin Roran on a farm near the village of Carvahall, ever since his mother, Garrow''s sister, left him there right after his birth. While hunting in the Spine, Eragon is surprised to see the blue dragon egg, which he believes to be a stone, appear in front of him. A few months later, Eragon witnesses a baby dragon hatch from the egg. Eragon names the Dragon Saphira. He raises the dragon in secret until two of King Galbatorix''s servants, the Ra''zac, come to Carvahall looking for the egg. Eragon and Saphira manage to escape by hiding in the Spine, but Garrow is fatally wounded and the house and farm are burned down by the Ra''zac. Once Garrow dies, Eragon is left with no reason to stay in Carvahall, so he goes after the Ra''zac with his newly hatched dragon, seeking vengeance for the destruction of his home and his uncle''s death. He is accompanied by Brom, an elderly storyteller, who provides Eragon with the sword Zar''roc and insists on helping him and Saphira. Later that night, their camp is ambushed by the Ra''zac. A stranger named Murtagh rescues them, but Brom is gravely injured. Saphira watches over Brom as the night progresses, yet when morning comes they realize there is nothing they can do to save him. Brom gives Eragon his blessing, reveals that he was also once a dragon rider and dies.The Kull reach Eragon right outside the Varden''s entrance, but are driven off with the help of the Varden, who escort Eragon, Saphira, Murtagh, and Arya to Farthen Dûr. When they arrive in Farthen Dûr, Eragon is led to the leader of the Varden, Ajihad. Ajihad imprisons Murtagh after he refuses to allow his mind to be read to determine if he is a friend or a foe to the Varden.
He and the Varden are then attacked by the Kull. Eragon personally battles Durza again, and does succeed in stabbing him the heart with Zar''roc, but at a price. Durza manages to give a deep cut like Murtagh''s on his back. He then passes out, and is visited by a stranger while he is unconscious who tells him to come to him at Ellesmãria. Eragon decides to do just that.',
'Fantasy'),
-- Tell me your dreams - Sidney Sheldon
('Tell me your dreams', 'Sidney', 'Sheldon', 1999, 'William Morrow', 
'The main characters of the book are Ashley Patterson, an introverted workaholic, her co-workers, Toni Prescott, an outgoing singer and dancer, and shy artist Alette Peters and Ashley''s father.
The three women do not get along very well, because of their dissimilar natures. Toni and Alette generally maintain a friendship, with Alette a calming influence, but Toni dislikes Ashley and criticizes her harshly. All three have issues with their mothers having told them they''d never amount to anything.
Ashley fears that somebody is following her. She finds her house lights turned on when she returns from work, her personal effects in disarray, and someone has written "You will die" on her mirror with a lipstick. She thinks someone''s broken into her house. She requests a police escort, but the next morning, the police officer assigned to this duty is found dead in her apartment. Two other murders have already taken place, with an identical pattern. All the murdered men had been castrated and were having sex before being murdered. Evidence points to the same woman being involved in all three cases. When a gift from one of the murdered men to Toni is found among Ashley''s things, she is identified as the killer and arrested. At this point, it is revealed that the three women are three selves of a woman suffering from multiple personality disorder.',
'Thriller'),
-- Memoirs of a geisha - Arthur Golden
('Memoirs of a geisha', 'Arthur', 'Golden', 1997,'Alfred A. Knopf', 
'At the age of nine, Chiyo Sakamoto is taken from her poverty-stricken fishing village of Yoroido on the coast of the Sea of Japan with her older sister Satsu and sold to an okiya (geisha boarding house) in Gion, the most prominent geisha district in Kyoto. Perceived as less attractive in looks and demeanor, Satsu is not sold into the okiya and is instead forced into becoming a prostitute in Kyoto''s pleasure district. Chiyo lives in the okiya alongside another young girl named Pumpkin, the elderly and grumbling Granny, money-obsessed Mother, and Auntie, a failed geisha. Also living in the okiya is the famous and ill-mannered geisha, Hatsumomo. She promptly takes to disliking Chiyo, who she sees as a potential future rival who may threaten her place in the okiya and Gion, as well as Mother''s financial dependence upon her earnings. Hatsumomo begins to go out of her way to get rid of Chiyo.Sayuri eventually meets the Chairman again and reveals that her acts in Amami were for personal reasons. He reveals to Sayuri that he had always had feelings towards her, despite her thinking he didn''t, but explains that he felt it disrespectful to take away the woman his friend had showed so much interest in, especially considering Nobu had once saved the Chairman''s company. He also reveals that he found out the truth after confronting Pumpkin and told Nobu afterwards, causing Nobu to cease becoming Sayuri''s danna. Sayuri and the Chairman kiss, which she feels is her first kiss expressing true love.
Sayuri eventually retires from being a geisha and the Chairman becomes her danna. It is revealed that they have an illegitimate son together. Foreseeing the consequences this could have regarding the inheritance of Iwamura Electric, she relocates to New York City in later life. Here she opens her own small tea house for entertaining Japanese men on business in the United States, in which Mother takes a financial interest, but Sayuri severs her links to the Nitta okiya and in effect, Japan. The Chairman remains her danna until his death and the story concludes with a reflection on Sayuri/Chiyo and her life.',
'Drama'),
-- Girl with a pearl earring - Tracy Chevalier
('Girl with a pearl earring', 'Tracy', 'Chevalier', 1999,'HarperCollins',
'Sixteen-year-old Griet lives with her family in Delft in 1664. Her father has been recently blinded in an accident, and the family''s precarious economic situation forces Griet''s parents to find her employment as a maid in painter Johannes Vermeer''s household. Becoming a maid casts doubt on Griet''s respectability because of the bad reputation that maids have for stealing, spying and sleeping with their employers. It is not revealed how much of this reputation is earned. At the Vermeers, she befriends the family''s oldest daughter, Maertge, but is not on good terms with Cornelia, one of Vermeer''s younger daughters. She also becomes friendly with Tanneke, the other house servant, but is careful to remain modest and unobtrusive for fear of making Tanneke jealous.
During her months of work at the Vermeers'', Pieter, the local butcher''s son, starts courting Griet, and the area in which Griet''s family lives is struck with plague which leads to the death of her younger sister. Griet is increasingly fascinated by Vermeer''s paintings. Vermeer discovers that Griet has an eye for art, and secretly asks her to run errands and perform tasks for him, such as mixing his paints and acting as a substitute model. Griet arouses the suspicions of Vermeer''s wife, Catharina, but Vermeer''s mother-in-law recognizes Griet''s presence as a steadying and catalyzing force in Vermeer''s career. Griet is warned by Vermeer''s friend, Dr. van Leeuwenhoek, not to get too close to Vermeer because Vermeer is far more interested in paintings than he is in people. Griet realizes that this is true and remains cautious.
Vermeer''s wealthy but licentious patron, Van Ruijven, notices Griet and her beauty and pressures Vermeer to paint them sitting together. Griet and Vermeer are initially reluctant to fulfill this request due to Griet''s strict modesty and a scandal surrounding the last girl who had been painted with van Ruijven. Eventually, Vermeer comes up with a compromise and paints a portrait of Griet by herself to be sold to van Ruijven. For the painting, he asks her to wear his wife''s pearl earrings. When Catharina discovers this, Griet is forced to leave.
Ten years later, long after Griet has married Pieter and settled into life as a mother and butcher''s wife, she is called back to the house upon Vermeer''s death. Griet assumes that Vermeer''s widow wishes to settle the household''s unpaid fifteen-guilder bill with the butcher shop. Pieter laughs and says that he didn''t mind losing the fifteen guilders because they bought him Griet as a wife. She then pawns the earrings for twenty guilders and pays fifteen guilders to her husband, claiming that Vermeer''s widow had given her the coins to settle a debt with the butcher shop, but keeps five guilders to herself and never spends them.',
'Drama'),
-- Les Miserables - Victor Hugo
('Les Miserables','Victor', 'Hugo', 1862,'A. Lacroix, Verboeckhoven & Cie.', 
'Les Miserables is is considered one of the greatest novels of the 19th century. In the English-speaking world, the novel is usually referred to by its original French title, however several alternatives have been used, including The Miserable, The Wretched, The Miserable Ones, The Poor Ones, The Wretched Poor, The Victims and The Dispossessed. Beginning in 1815 and culminating in the 1832 June Rebellion in Paris, the novel follows the lives and interactions of several characters, particularly the struggles of ex-convict Jean Valjean and his experience of redemption.[2]
Examining the nature of law and grace, the novel elaborates upon the history of France, the architecture and urban design of Paris, politics, moral philosophy, antimonarchism, justice, religion, and the types and nature of romantic and familial love. Les Misérables has been popularized through numerous adaptations for the stage, television, and film, including a musical and a film adaptation of that musical.
The appearance of the novel was highly anticipated and advertised. Critical reactions were diverse, but most of them were negative. Commercially, the work was a great success globally.',
'Drama'),
-- A walk to remember - Nicholas Sparks
('A walk to remember', 'Nicholas', 'Sparks', 2002, 'Warner books',
'The story starts with a prologue from Landon Carter at age 57. The remainder of the story takes place when Landon is a 17-year-old high school senior.[7] Landon lives in the small, religious town of Beaufort, North Carolina.[8] His father is a genial, charismatic congressman.
His father is not around very much, as he lives in Washington, D.C. Landon is more reclusive, which causes some tension in their relationship. Landon''s father pressures him into running for class president.[10] His best friend, Eric Hunter, who is the most popular boy in school, helps him and, to his surprise, Landon wins the election. As student body president, Landon is required to attend the school dance with a date.[11] He asks many girls, but none are available. That night, he looks through his yearbook, trying to find an acceptable date. Since nobody else seems to be available, Landon reluctantly asks Jamie Sullivan, the daughter of Hegbert Sullivan, the Beaufort church minister,[13] who accepts his invitation.[14] While Jamie is very religious and carries a Bible with her wherever she goes, Landon (one of the popular students) is reluctant to go to the dance with someone like her. When Landon is threatened by Lew,[15] Jamie comes to Landon''s aid, to his appreciation. At the end of the night, he admits she was the best date possible.The following Sunday, Hegbert announces to his congregation that his daughter is dying.[40] Jamie does not return to school the following Monday and that it is eventually learned that she is too ill and will never return to school.[41] While they are having dinner at Landon''s house, Jamie tells Landon, "I love you, too," for the first time.[42] A couple weeks later, Eric and Margaret visit Jamie''s house, where they apologize for ever being rude to her.[43] Eric gives Jamie the $400 that he collected for the orphanage.[44] Jamie refuses to stay at the hospital, because she wants to die at home. In turn, Landon''s father helps to provide Jamie the best equipment and doctors so she can spend the rest of her life at home.[45] This gesture helps to mend the gap between father and son. One day, while sitting next to Jamie while she sleeps, Landon comes up with an idea.[46] He runs to the church to find Hegbert[47] and asks him for permission to marry Jamie. While Hegbert is reluctant,[48] his refusal to deny Landon''s request is seen by Landon as approval. Landon runs back to Jamie''s side and asks, "Will you marry me?"
Landon and Jamie are married in a church full of people. Although she was weak and was in a wheelchair, she insisted on walking down the aisle so that her father could give her away which was part of her dream.[51] Landon remembers thinking "It was...the most difficult walk anyone ever had to make. In every way, a walk to remember."When they reach the front of the church, Hegbert says, "I can no more give Jamie away than I can give away my heart. But what I can do is let another share in the joy that she has always given me."Hegbert has had to experience so much pain in his life, first losing his wife, now knowing his only child will soon be gone, too. The book ends with Landon 40 years later at age 57. He still loves Jamie and wears her ring.[54] He finishes the story by saying, "I now believe, by the way, that miracles can happen.',
'Romance'),
-- The Notebook - Nicholas Sparks
('The Notebook', 'Nicholas', 'Sparks', 1996,'Warner books', 
'The novel opens with Noah Calhoun, an old man, reading to a woman in a nursing home. He tells her the following story:
Noah, 31, returns from World War II. He finishes restoring an antebellum-style house, after his father''s death. Meanwhile Allie, 29, sees the house in the newspaper and decides to pay him a visit.
They are meeting, again, after a 14-year separation, which followed their brief but passionate summer romance when her family was visiting the town. They were separated by class, as she was the daughter of a wealthy family, and he worked as a laborer in a lumberyard. Seeing each other brings on a flood of memories and strong emotions in both of them. They have dinner together and talk about their lives and the past. The man stops reading the story at this point, and tells the reader that he is reading to his wife, who suffers from Alzheimer''s disease and does not recognize him. He explains that he is also ill, battling a third cancer, and suffering heart disease, kidney failure, and severe arthritis in his hands.
Recognizing her husband, she tells him that she loves him. They embrace and talk, but after almost four hours, Allie fades. She begins to panic and hallucinate. She forgets who Noah is again. A week later, after he had a stroke and recovered, Noah goes to Allie''s room at night to see her. She remembered who he was, despite the Alzheimer''s, and she says that she had missed Noah. Noah realises it is just a ruse to let him go see Allie and he finds Allie in bed in her room, asleep.
In the morning they are still on the bed holding hands, the nurse goes in and sees them with their eyes closed and touches their held hands and realizes they are both dead.',
'Romance'),
-- Harry Potter - J.K.Rowling
('Harry Potter and the Philosopher''s Stone', 'J.K.', 'Rowling', 1997,'Bloomsbury', 
'The plot follows Harry Potter, a young wizard who discovers his magical heritage as he makes close friends and a few enemies in his first year at the Hogwarts School of Witchcraft and Wizardry. With the help of his friends, Harry faces an attempted comeback by the dark wizard Lord Voldemort, who killed Harry''s parents, but failed to kill Harry when he was just a year old.
The book, which was Rowling''s debut novel, was published on 26 June 1997 by Bloomsbury in London. In 1998, Scholastic Corporation published an edition for the United States market under the title Harry Potter and the Sorcerer''s Stone. The novel won most of the British book awards that were judged by children, and other awards in the US. The book reached the top of the New York Times list of best-selling fiction in August 1999, and stayed near the top of that list for much of 1999 and 2000. It has been translated into several other languages and has been made into a feature-length film of the same name.
Most reviews were very favourable, commenting on Rowling''s imagination, humour, simple, direct style and clever plot construction, although a few complained that the final chapters seemed rushed. The writing has been compared to that of Jane Austen, one of Rowling''s favourite authors, or Roald Dahl, whose works dominated children''s stories before the appearance of Harry Potter, and of the Ancient Greek story-teller Homer. While some commentators thought the book looked backwards to Victorian and Edwardian boarding school stories, others thought it placed the genre firmly in the modern world by featuring contemporary ethical and social issues.
Harry Potter and the Philosopher''s Stone, along with the rest of the Harry Potter series, has been attacked by several religious groups and banned in some countries because of accusations that the novels promote witchcraft, but some Christian commentators have written that the book exemplifies important Christian viewpoints, including the power of self-sacrifice and the ways in which people''s decisions shape their personalities. The series has been used as a source of object lessons in educational techniques, sociological analysis and marketing.',
'Fantasy'),
-- Lord of the Rings - J.R.R.Tolkien
('The Fellowship of the Ring', 'J.R.R.', 'Tolkien', 1954,'George Allen & Unwin',
'The first chapter in the book begins in a light vein, following the tone of The Hobbit. Bilbo Baggins celebrates his 111th (or eleventy-first, as it is called in Hobbiton) birthday on the same day, 22 ''September'', that his younger cousin and adopted heir Frodo Baggins celebrates his coming of age at 33. At the birthday party, Bilbo departs from the Shire, the land of the Hobbits, for what he calls a permanent holiday. Bilbo does so by using the magic ring (that he had found on his journey) to disappear and is aided by Gandalf with a flash and puff of smoke, leading many in the Shire to believe he has gone mad. He leaves Frodo his remaining belongings, including his home, Bag End, and (after some persuasion by the wizard Gandalf) the Ring. Gandalf leaves on his own business, warning Frodo to keep the Ring secret.
Over the next 17 years Gandalf periodically pays short visits to Bag End. One spring night, he arrives to enlighten Frodo about Bilbo''s ring; it is the One Ring of Sauron the Dark Lord. Sauron had forged it to subdue and rule Middle-earth, but in the War of the Last Alliance, he had been defeated by Gil-galad the Elven King and Elendil, High King of Arnor and Gondor, though they themselves perished in the deed. Isildur, Elendil''s son, cut the Ring from Sauron''s finger. Sauron had thus been overthrown, but the Ring itself was not destroyed as it should have been; Isildur kept it for himself. Isildur was slain soon afterwards in the Battle of the Gladden Fields, and the Ring was lost in Great River Anduin. Thousands of years later, it had been found by the hobbit Déagol; but Déagol was thereupon murdered by his friend Sméagol, who coveted the Ring for himself. Sméagol subsequently possessed the Ring for centuries, and under its influence he became the creature named Gollum. The Ring was found by Bilbo Baggins, as told in The Hobbit, and Bilbo left it behind for Frodo.',
'Fantasy'),
-- The Girl with the Dragon Tattoo - Stieg Larsson
('The Girl with the Dragon Tattoo', 'Stieg', 'Larson', 2005,'Norstedts Forlag',
'Larsson spoke of an incident which he said occurred when he was 15: he stood by as three men gang-raped an acquaintance of his named Lisbeth. Days later, racked with guilt for having done nothing to help her, he begged her forgiveness — which she refused. The incident, he said, haunted him for years afterward, and in part inspired him to create a character named Lisbeth who was also a rape survivor.[2][3] The veracity of this story has been questioned since Larsson''s death, after a colleague from Expo magazine reported to Rolling Stone that Larsson had told him that he had heard the story secondhand and retold it as his own.[4]
With the exception of the fictional Hedestad, the novel takes place in true Swedish towns. The magazine Millennium in the books has characteristics similar to that of Larsson''s magazine, Expo, such as its financial difficulties.[citation needed]
Both Larsson''s longtime partner Eva Gabrielsson and English translator Steven T. Murray have said that Christopher Maclehose (who works for British publisher Quercus) "needlessly prettified" the English translation, this being the reason Murray requested he be credited under the pseudonym "Reg Keeland."[6] The English release also changed the title, even though Larsson specifically refused to allow the Swedish publisher to do so, and the size of Salander''s dragon tattoo; from a large piece covering her entire back, to a small shoulder tattoo',
'Thriller'),
-- The Girl who played with fire - Stieg Larsson
('The girl who played with fire', 'Stieg', 'Larson', 2006,'Norstedts Forlag',
'After finishing the job on the Wennerström affair (described in The Girl with the Dragon Tattoo), Lisbeth Salander disappeared from Sweden and traveled throughout Europe. The novel opens with her on the shores of the Caribbean in St George''s, the capital of Grenada. Salander has become interested in Fermat''s Last Theorem and mathematics, an interest that resounds with the opening page of each Part in this novel. From within her room in her hotel she observes on several occasions that her neighbor, Dr Forbes, an American tourist from Texas, physically abuses his wife, in the next room to Salander. She also befriends George Bland, a sixteen-year-old orphaned student living in a small shack, and begins tutoring him in mathematics. Salander finds Bland''s company relaxing and enjoyable because Bland does not ask her personal questions, and the two develop a sexual relationship.
Salander uses her connections among the hackers'' network to investigate Dr Forbes and learns that he was once accused of mishandling funds in his faith-based foundation. Currently he has no assets, but his wife is the heir to a fortune worth $40 million. Concerns for the safety of the residents at the hotel cause the hotel management to begin ushering them into a cellar as a hurricane hits Grenada. Salander remembers Bland and braves the strong wind and rain to collect him. As the two reach the hotel entrance, Salander sees Dr Forbes on the beach with his wife and realizes that he is attempting to kill her for her inheritance. Salander attacks Forbes with the leg of a chair, and abandons him to the elements. Salander, Bland and Mrs Forbes retreat to the cellar and receive medical care; Dr Forbes is later confirmed as the only fatality of the storm.',
'Thriller'),
-- The Black Cat - Edgar Allan Poe
('The Black Cat', 'Edgar Allan', 'Poe', 1843,'United States Saturday Post',
'The story is presented as a first-person narrative using an unreliable narrator. He is a condemned man at the outset of the story.[3] The narrator tells us that from an early age he has loved animals. He and his wife have many pets, including a large, beautiful black cat (as described by the narrator) named Pluto. This cat is especially fond of the narrator and vice versa. Their mutual friendship lasts for several years, until the narrator becomes an alcoholic. One night, after coming home completely intoxicated, he believes the cat to be avoiding him. When he tries to seize it, the panicked cat bites the narrator, and in a fit of rage, he seizes the animal, pulls a pen-knife from his pocket, and deliberately gouges out the cat''s eye.
From that moment onward, the cat flees in terror at his master''s approach. At first, the narrator is remorseful and regrets his cruelty. "But this feeling soon gave place to irritation. And then came, as if to my final and irrevocable overthrow, the spirit of perverseness." He takes the cat out in the garden one morning and ties a noose around its neck, hanging it from a tree where it dies. That very night, his house mysteriously catches fire, forcing the narrator, his wife and their servant to flee the premises. On the last day of the investigation, the narrator accompanies the police into the cellar. They still find nothing significant. Then, completely confident in his own safety, the narrator comments on the sturdiness of the building and raps upon the wall he had built around his wife''s body. A loud, inhuman wailing sound fills the room. The alarmed police tear down the wall and find the wife''s corpse, and on rotting head, to the utter horror of the narrator, is the screeching black cat. As he words it: "I had walled the monster up within the tomb!".',
'Horror'),
-- The Hobbit - J.R.R Tolkien
('The Hobbit','J.R.R.','Tolkien', 1937,'Unwin',
'Gandalf tricks Bilbo into hosting a party for Thorin and his band of dwarves, who sing of reclaiming the Lonely Mountain and its vast treasure from the dragon Smaug. When the music ends, Gandalf unveils a map showing a secret door into the Mountain and proposes that the dumbfounded Bilbo serve as the expedition''s "burglar". The dwarves ridicule the idea, but Bilbo, indignant, joins despite himself.
The group travels into the wild, where Gandalf saves the company from trolls and leads them to Rivendell, where Elrond reveals more secrets from the map. Passing over the Misty Mountains, they are caught by goblins and driven deep underground. Although Gandalf rescues them, Bilbo gets separated from the others as they flee the goblins. Lost in the goblin tunnels, he stumbles across a mysterious ring and then encounters Gollum, who engages him in a game of riddles. As a reward for solving all riddles Gollum will show him the path out of the tunnels, but if Bilbo fails, his life will be forfeit. With the help of the ring, which confers invisibility, Bilbo escapes and rejoins the dwarves, improving his reputation with them. The goblins and Wargs give chase but the company are saved by eagles before resting in the house of Beorn.
The company enters the black forest of Mirkwood without Gandalf. In Mirkwood, Bilbo first saves the dwarves from giant spiders and then from the dungeons of the Wood-elves. Nearing the Lonely Mountain, the travellers are welcomed by the human inhabitants of Lake-town, who hope the dwarves will fulfil prophecies of Smaug''s demise. The expedition travels to the Lonely Mountain and finds the secret door; Bilbo scouts the dragon''s lair, stealing a great cup and learning of a weakness in Smaug''s armour. The enraged dragon, deducing that Lake-town has aided the intruder, sets out to destroy the town. A thrush had overheard Bilbo''s report of Smaug''s vulnerability and reports it to Lake-town defender Bard. His arrow finds the chink and slays the dragon.
When the dwarves take possession of the mountain, Bilbo finds the Arkenstone, an heirloom of Thorin''s dynasty, and hides it away. The Wood-elves and Lake-men besiege the mountain and request compensation for their aid, reparations for Lake-town''s destruction, and settlement of old claims on the treasure. Thorin refuses and, having summoned his kin from the mountains of the North, reinforces his position. Bilbo tries to ransom the Arkenstone to head off a war, but Thorin is intransigent. He banishes Bilbo, and battle seems inevitable.
Gandalf reappears to warn all of an approaching army of goblins and Wargs. The dwarves, men and elves band together, but only with the timely arrival of the eagles and Beorn do they win the climactic Battle of Five Armies. Thorin is fatally wounded and reconciles with Bilbo before he dies. Bilbo accepts only a small portion of his share of the treasure, having no want or need for more, but still returns home a very wealthy hobbit.',
'Fantasy'),
-- Faceless Killers - Mankell Henning
('Faceless Killers', 'Henning', 'Mankell', 1991,'Ordfront',
'Inside an almost isolated Skåne farmhouse in Lunnarp, an old man, Johannes Lövgren, is tortured to death and his wife Maria savagely beaten and left for dead with a noose around her neck. Inspector Kurt Wallander, a forty-two-year-old Ystad police detective, and his team – Rydberg, an aging detective with rheumatism; Martinsson, a 29-year-old rookie; Naslund, a thirty-year veteran; Svedberg, a balding, forty-something-year-old detective; Hansson; and Peters – are put on the case. Maria Lovgren is taken to hospital, but dies anyway. Her last word: "foreign".
Rydberg has been examining the noose around Mrs Lovgren''s neck and "has never seen one like it before". He thinks that Mrs Lovgren''s last word is accurate, and that the murderers are foreign. But his conclusion leads to several racially-motivated attacks after the information is leaked to the press.
The story focuses on Sweden''s liberal attitude regarding immigration, and explores themes of racism and national identity.',
'Horror'),
-- Call of Cthulhu - H. P. Lovecraft
('Call of Cthulhu', 'H. P.', 'Lovecraft', 1928,'Weird Tales',
'In the text, narrator Francis Wayland Thurston, of Boston, recounts his discovery of notes left behind by his granduncle, George Gammell Angell, a prominent Professor of Semitic languages at Brown University in Providence, Rhode Island, who died suddenly in "the winter of 1926–27" after being "jostled by a nautical-looking negro".',
'Horror'),
-- Fight Club - Chuck Palahniuk
('Fight Club', 'Chuck', 'Palahniuk', 1996,'W. W. Norton',
'Fight Club centers on an anonymous narrator, who works as a product recall specialist for an unnamed car company. Because of the stress of his job and the jet lag brought upon by frequent business trips, he begins to suffer from recurring insomnia. When he seeks treatment, the narrator''s doctor advises him to visit a support group for testicular cancer victims to "see what real suffering is like". The narrator finds that sharing the problems of others—despite not actually having testicular cancer himself—alleviates his insomnia.',
'Drama');
